### ISSUE TITLE
Why don't you make an extension that could be used on any website?

### ISSUE THREAD

**Issue by mrkway** [Ordinath/Whisper_to_ChatGPT#1]
It seems there isn't one out there. 

Besides, I haven't found any other solution to get around the 25 MB limitation, so I'm using [Whisper_to_ChatGPT] even for transcribing longer, non-ChatGPT related stuff.

**Comment by Ordinath** [comment]
Hey there! 
I don't think this is the way forward for this chrome extension. I see this as a ChatGPT utility only. 
But you are on the right path and maybe someone, you or myself would come up with a desktop MacOS/Windows menubar tool, that could do the same thing and just copy it to clipboard :)
