### ISSUE TITLE
429 ERROR

### ISSUE THREAD

**Issue by khamaileon** [Ordinath/Whisper_to_ChatGPT#12]
The extension no longer works for me. I've tried with a new token but without success.

I've got this message:

429 ERROR! API key not provided or OpenAI Server Error! Check the Pop-up window of the Extension to provide API key.

**Comment by spirittechie** [comment]
I am getting the same error.

**Comment by Ordinath** [comment]
Hey guys, the issue is most probably occurring due to the changed OpenAI billing system to be prepaid. 
Since a couple of days you need to have a positive balance on the account for your API keys to work.

**Comment by maestrocoder** [comment]
Yes @Ordinath is correct.  Great extension and thanks for making it open!!!  I am enjoying learning from your code on this useful chrome extension!!! At first I uninstalled extension, remade the key 3 times, etc.. nothing.  Also did a separate test and got the same results, so confirming not the extension.  It's weird that openai changed to credits (missed that memo), even if you have been paying openai for a year and using this extension, then suddenly you have to go into your account and prepay, add $20.  Refresh/reload extension or chatgpt browser and then it works again.  

Openai -> Settings -> Billing -> Add Credit Balance

**Comment by sanity** [comment]
I've tried this, added $20 to credit balance - restarted my browser but I'm still getting:

```
429 ERROR! API key not provided or OpenAI Server Error! Check the Pop-up window of the Extension to provide API key.
```
