### ISSUE TITLE
Idea: enable on any textarea

### ISSUE THREAD

**Issue by JCharante** [Ordinath/Whisper_to_ChatGPT#13]
I love using whisper and think that adding the microphone icon to any textarea input would make it so useful to use on other sites. I'm not experienced with browser extensions, but this might inspire somebody out there.

**Comment by Mindsurfer7** [comment]
i agree

**Comment by OLH21** [comment]
would be nice to have la global shortcut to work anywhere or even system wide other application do this ;)

**Comment by Wizek** [comment]
I could look into implementing this in some way, @Ordinath would you be interested in a pull request?

**Comment by Ordinath** [comment]
Hello guys! I don't mind you taking this and forking it to make this capability happen, but it's already a bit too much for me to maintain the constant ChatGPT website changes, so I have to pass here. 
This extension will stay ChatGPT only, probably forever.
