### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by khamaileon** [Ordinath/Whisper_to_ChatGPT#2]
Thank you very much for this great extension. Is there a way to activate or deactivate the microphone using a keyboard shortcut?
As I was writing this message, I was thinking how cool it would be to be able to write it using Whisper too :)

**Comment by Ordinath** [comment]
Hey there!
Thanks, and that's a good idea! I'll add this once I get some spare time 🙂

**Comment by idnotbe** [comment]
the keyboard shortcut is a must.

another feature i want is text-to-speach.
besides the mic button, there should be a speaker button.
when the speaker button is activated, it speaks the text form ChatGPT.
the text-to-speach is from another library such as ElevenLabs that needs another API key.

**Comment by Ordinath** [comment]
Hey there! 
Google finally concluded the review of 1.2.5 and the mic shortcut is there in the Web Store!
Regarding the text-to-speech, don't see this to be super useful for common use-cases, although it might come into scope at some point. At any rate, there are a lot of cool extensions, that already do this, just google for it.

**Comment by khamaileon** [comment]
@Ordinath I just tested it and it works great! Thank you very much :+1: :1st_place_medal:
