### ISSUE TITLE
Loader stucks sometimes

### ISSUE THREAD

**Issue by khamaileon** [Ordinath/Whisper_to_ChatGPT#4]
Sometimes the loader keeps spinning indefinitely. I guess Whisper didn't respond or returned an error. Maybe it would be useful to add a timeout with maybe an error message?

**Comment by Ordinath** [comment]
Curious, I thought I fixed this previously. Could you provide steps to reproduce?

**Comment by khamaileon** [comment]
It is working for me right now but you can simulate it by turning off WIFI. If you turn it on again, the loader keeps spinning.

**Comment by Ordinath** [comment]
It's difficult to determine the appropriate timeout condition, as the transcription process may take an extended amount of time, depending on the length of the sound file being sent. 
I will consider this and see what I can do, but I must note that this issue won't be a priority.
